# -*- coding: utf-8 -*-
"""cancer10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0cNkDqpqv1U7WjcUEyzUhBivm4Mf-_J
"""

# app.py

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# ------------------------------
# App Title
# ------------------------------
st.set_page_config(page_title="Cancer Prediction App", layout="wide")
st.title("🧬 Cancer Prediction App")
st.write("Machine Learning based cancer prediction using patient data")

# ------------------------------
# Load Dataset
# ------------------------------
@st.cache_data
def load_data():
    try:
        data = pd.read_csv("cancer_prediction.csv")  # CSV must be in the same folder as app.py
        return data
    except FileNotFoundError:
        st.error("⚠️ cancer_prediction.csv not found. Please upload it in the repo folder.")
        return None

df = load_data()

if df is not None:
    # Show dataset preview
    st.subheader("📊 Dataset Preview")
    st.dataframe(df.head())

    # ------------------------------
    # Select Target Column
    # ------------------------------
    target = st.selectbox("Select Target Column", df.columns)

    X = df.drop(columns=[target])
    y = df[target]

    # ------------------------------
    # Train-Test Split & Scaling
    # ------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # ------------------------------
    # Model Training
    # ------------------------------
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train_scaled, y_train)

    # Model Accuracy
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    st.success(f"✅ Model Accuracy: {accuracy * 100:.2f}%")

    # ------------------------------
    # User Input for Prediction
    # ------------------------------
    st.subheader("🧪 Enter Patient Data for Prediction")
    user_input = []
    for col in X.columns:
        min_val = float(df[col].min())
        max_val = float(df[col].max())
        step_val = (max_val - min_val) / 100  # smaller step for float inputs
        value = st.number_input(f"{col}", min_value=min_val, max_value=max_val, step=step_val)
        user_input.append(value)

    if st.button("Predict Cancer"):
        input_array = np.array(user_input).reshape(1, -1)
        input_scaled = scaler.transform(input_array)
        prediction = model.predict(input_scaled)

        if prediction[0] == 1:
            st.error("⚠️ Cancer Detected (Malignant)")
        else:
            st.success("✅ No Cancer Detected (Benign)")