# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqBjzxnXO3ERN71ZQ9W2H2bqCOWn-OnA
"""
!pip install streamlit pandas numpy scikit-learn matplotlib seaborn


"""STREAMLIT APP CODE"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# App title
st.title("🧬 Cancer Prediction App")
st.write("Machine Learning based cancer prediction using patient data")

# Load dataset
@st.cache_data
def load_data():
    data = pd.read_csv("cancer prediction.csv")
    return data

df = load_data()

# Show dataset
st.subheader("📊 Dataset Preview")
st.dataframe(df.head())

# Select target column
target = st.selectbox("Select Target Column", df.columns)

X = df.drop(columns=[target])
y = df[target]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
model = LogisticRegression()
model.fit(X_train, y_train)

# Accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

st.success(f"✅ Model Accuracy: {accuracy * 100:.2f}%")

# User Input Section
st.subheader("🧪 Enter Patient Data")

user_input = []
for col in X.columns:
    value = st.number_input(f"{col}", float(df[col].min()), float(df[col].max()))
    user_input.append(value)

# Prediction
if st.button("Predict Cancer"):
    input_array = np.array(user_input).reshape(1, -1)
    input_scaled = scaler.transform(input_array)
    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Cancer Detected (Malignant)")
    else:
        st.success("✅ No Cancer Detected (Benign)")
