# -*- coding: utf-8 -*-
"""health insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCE49AIc44_z9lE3zxzeeGCtFOYUyMUr
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Page configuration
st.set_page_config(
    page_title="Health Insights Dashboard",
    layout="wide"
)

# App title
st.title("Health Insights Dashboard")
st.write("Interactive visualization of healthcare data")

# Sample healthcare data (you can replace this with your dataset)
data = {
    "Year": [2018, 2019, 2020, 2021, 2022],
    "Deaths": [1200, 1350, 1600, 1500, 1400],
    "Disease": ["Communicable"] * 5
}

df = pd.DataFrame(data)

# Show data table
st.subheader("Dataset Preview")
st.dataframe(df)

# Plotly line chart
st.subheader("Mortality Trend Over Years")

fig = px.line(
    df,
    x="Year",
    y="Deaths",
    markers=True,
    title="Year-wise Mortality Trend"
)

st.plotly_chart(fig, use_container_width=True)

# Footer
st.markdown("---")
st.caption("Developed using Streamlit & Plotly")