# -*- coding: utf-8 -*-
"""health insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCE49AIc44_z9lE3zxzeeGCtFOYUyMUr
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

# 1. PAGE CONFIG (Must be the first Streamlit command)
st.set_page_config(
    page_title="OncoVision AI Platform",
    page_icon="🎗️",
    layout="wide"
)

# 2. DATA & MODEL INITIALIZATION
@st.cache_resource
def initialize_app():
    # Load dataset
    if not os.path.exists('cancer_prediction.csv'):
        return None, None

    df = pd.read_csv('cancer_prediction.csv')

    # Train model if not already saved
    model_path = 'cancer_model.joblib'
    if os.path.exists(model_path):
        model = joblib.load(model_path)
    else:
        X = df.drop('Diagnosis', axis=1)
        y = df['Diagnosis']
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X, y)
        joblib.dump(model, model_path)

    return df, model

df, model = initialize_app()

# 3. SIDEBAR NAVIGATION
st.sidebar.title("🏥 OncoVision AI")
st.sidebar.markdown("---")
page = st.sidebar.radio("Main Menu", ["📊 Analytics Dashboard", "🧪 Risk Predictor", "📄 Project Info"])

if df is None:
    st.error("Critical Error: 'cancer_prediction.csv' not found. Please ensure it is in the same folder.")
    st.stop()

# 4. ANALYTICS DASHBOARD
if page == "📊 Analytics Dashboard":
    st.title("📊 Clinical Population Analytics")
    st.markdown("Trends and correlations derived from the hospital dataset.")

    if df is not None:
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Records", len(df))
        col2.metric("Cancer Prevalence", f"{(df['Diagnosis'].mean()*100):.1f}%")
        col3.metric("Avg Patient BMI", f"{df['BMI'].mean():.1f}")

        st.markdown("---")

        row1_c1, row1_c2 = st.columns(2)
        with row1_c1:
            st.subheader("Age Distribution by Diagnosis")
            fig1 = px.histogram(df, x="Age", color="Diagnosis", barmode="overlay",
                                color_discrete_map={0: "#2ecc71", 1: "#e74c3c"},
                                labels={"Diagnosis": "Result (1=Cancer)"})
            st.plotly_chart(fig1, use_container_width=True)

        with row1_c2:
            st.subheader("Genetic Risk Impact")
            fig2 = px.sunburst(df, path=['GeneticRisk', 'Diagnosis'], color='Diagnosis',
                               color_continuous_scale='RdYlGn_r')
            st.plotly_chart(fig2, use_container_width=True)
    else:
        st.warning("Cannot display Analytics Dashboard: Data not loaded.")

# 5. RISK PREDICTOR
elif page == "🧪 Risk Predictor":
    st.title("🧪 Diagnostic Support Tool")
    st.write("Enter patient metrics to calculate a cancer risk probability score.")

    if df is not None and model is not None:
        with st.sidebar:
            st.header("Patient Entry")
            age = st.slider("Age", 18, 90, 45)
            gender = st.selectbox("Gender", ["Female", "Male"])
            bmi = st.number_input("BMI", 15.0, 45.0, 24.5)
            smoke = st.radio("Smoking Status", ["Non-smoker", "Smoker"])
            genetics = st.selectbox("Genetic Risk Level", ["Low", "Medium", "High"])
            activity = st.slider("Activity (Hrs/Week)", 0, 10, 4)
            alcohol = st.slider("Alcohol (Units/Week)", 0, 5, 1)
            history = st.radio("Family History of Cancer", ["No", "Yes"])

        # Prepare data
        input_df = pd.DataFrame({
            'Age': [age],
            'Gender': [1 if gender == "Male" else 0],
            'BMI': [bmi],
            'Smoking': [1 if smoke == "Smoker" else 0],
            'GeneticRisk': [{"Low": 0, "Medium": 1, "High": 2}[genetics]],
            'PhysicalActivity': [activity],
            'AlcoholIntake': [alcohol],
            'CancerHistory': [1 if history == "Yes" else 0]
        })

        if st.button("Generate Diagnostic Report"):
            prob = model.predict_proba(input_df)[0][1]

            c1, c2 = st.columns([1, 1])
            with c1:
                # Gauge Chart
                fig_gauge = go.Figure(go.Indicator(
                    mode = "gauge+number",
                    value = prob * 100,
                    title = {'text': "Risk Probability (%)"},
                    gauge = {
                        'axis': {'range': [0, 100]},
                        'bar': {'color': "darkblue"},
                        'steps' : [
                            {'range': [0, 35], 'color': "lightgreen"},
                            {'range': [35, 70], 'color': "orange"},
                            {'range': [70, 100], 'color': "red"}]}))
                st.plotly_chart(fig_gauge, use_container_width=True)

            with c2:
                st.subheader("Analysis Results")
                if prob > 0.65:
                    st.error("HIGH RISK: Patient shows high correlation with malignant profiles.")
                    st.markdown("- **Recommendation:** Immediate biopsy or MRI screening.")
                elif prob > 0.35:
                    st.warning("MODERATE RISK: Monitoring required.")
                    st.markdown("- **Recommendation:** Re-evaluate lifestyle and 6-month follow-up.")
                else:
                    st.success("LOW RISK: No immediate concern based on current parameters.")
    else:
        st.warning("Cannot use Risk Predictor: Data or model not loaded.")

# 6. ABOUT PAGE
else:
    st.title("📄 Project Information")
    st.info("This is a demo for Hospital Decision Support Systems.")
    st.markdown("""
    ### Technical Specification:
    - **Dataset:** Cancer Risk Prediction Clinical Records.
    - **Model:** Random Forest Classifier (Optimized for High Recall).
    - **Deployment:** Streamlit Cloud via GitHub.
    - **Developer Goal:** To provide clinicians with a visual and data-driven risk assessment tool.
    """)